apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sqlserver
      labels:
        app: sqlserver
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: sqlserver
      template:
        metadata:
          labels:
            app: sqlserver
        spec:
          containers:
            - name: sqlserver
              image: cagrin/azure-sql-edge-arm64
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 1433
              env:
                - name: ACCEPT_EULA
                  value: "Y"
                - name: MSSQL_SA_PASSWORD
                  value: "migsid-dokwew-jofQu5"
  - apiVersion: v1
    kind: Service
    metadata:
      name: sqlserver
    spec:
      type: ClusterIP
      selector:
        app: sqlserver
      ports:
        - protocol: TCP
          port: 1433
          targetPort: 1433
