// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api2.Data;

#nullable disable

namespace api2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240701162017_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api2.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = 2,
                            Isbn = "ISBN-123-456",
                            PublishedYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 2,
                            Genre = 3,
                            Isbn = "ISBN-321-456",
                            PublishedYear = 2003,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 3,
                            Genre = 2,
                            Isbn = "ISBN-456-123",
                            PublishedYear = 1997,
                            Title = "Harry Potter and the Philosopher's Stone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
